extension MemoryData {
    static let sample = Self(
        memoryPressure: .init(
            data: [
                .init(value: 40, level: .normal),
                .init(value: 41, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 39, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 39, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 41, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 41, level: .normal),
                .init(value: 41, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 41, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 40, level: .normal),
                .init(value: 41, level: .normal),
                .init(value: 42, level: .normal),
                .init(value: 43, level: .normal),
                .init(value: 44, level: .normal),
                .init(value: 44, level: .normal),
                .init(value: 43, level: .normal),
                .init(value: 42, level: .normal),
                .init(value: 45, level: .normal),
                .init(value: 48, level: .normal),
                .init(value: 49, level: .normal),
                .init(value: 52, level: .warning),
                .init(value: 55, level: .warning),
                .init(value: 54, level: .warning),
                .init(value: 55, level: .warning),
                .init(value: 56, level: .warning),
                .init(value: 58, level: .warning),
                .init(value: 56, level: .warning),
                .init(value: 55, level: .warning),
                .init(value: 60, level: .warning),
                .init(value: 63, level: .warning),
                .init(value: 63, level: .warning),
                .init(value: 68, level: .warning),
                .init(value: 71, level: .critical),
                .init(value: 76, level: .critical),
                .init(value: 80, level: .critical),
                .init(value: 78, level: .critical),
                .init(value: 82, level: .critical),
                .init(value: 85, level: .critical),
                .init(value: 73, level: .critical),
                .init(value: 60, level: .warning),
                .init(value: 52, level: .warning),
                .init(value: 38, level: .normal),
                .init(value: 28, level: .normal),
                .init(value: 22, level: .normal),
                .init(value: 22, level: .normal),
                .init(value: 23, level: .normal),
                .init(value: 24, level: .normal),
                .init(value: 24, level: .normal),
                .init(value: 23, level: .normal),
                .init(value: 21, level: .normal),
                .init(value: 22, level: .normal),
                .init(value: 22, level: .normal),
                .init(value: 21, level: .normal),
                .init(value: 22, level: .normal),
                .init(value: 22, level: .normal),
            ],
            capacity: 67
        ),
        physicalMemory: Int64(16.00 * 1_024 * 1_024 * 1_024),
        memoryUsed: Int64(12.26 * 1_024 * 1_024 * 1_024),
        appMemory: Int64(7.26 * 1_024 * 1_024 * 1_024),
        wiredMemory: Int64(3.35 * 1_024 * 1_024 * 1_024),
        compressed: Int64(819.3 * 1_024 * 1_024),
        cachedFiles: Int64(3.12 * 1_024 * 1_024 * 1_024),
        swapUsed: Int64(0)
    )
}
