opt_in_rules:
  - all
disabled_rules:
  - contrasted_opening_brace
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - force_unwrapping
  - identifier_name
  - implicitly_unwrapped_optional
  - no_grouping_extension
  - no_magic_numbers
  - prefixed_toplevel_constant
  - required_deinit
  - strict_fileprivate
  - trailing_comma
  - type_contents_order
  - vertical_whitespace_between_cases
closure_body_length:
  warning: 100
  error: 100
nesting:
  type_level:
    warning: 2
